dependencies {
    implementation project(':application')
    implementation project(':domain')
    implementation libs.boot.starter.webflux
    implementation libs.boot.springdoc.webflux
    implementation libs.projectlombok
    annotationProcessor libs.projectlombok
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
}